
spring:
  # 1. Primary DB (PostgreSQL) - Source Data & Batch Metadata
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_batch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # 2. Secondary DB (MySQL) - Target Data
  datasource-mysql:
    url: jdbc:mysql://localhost:3306/target_db
    username: root
    password: Piyush@l1 # Change this to your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      enabled: false # We run jobs manually via Controller
    jdbc:
      initialize-schema: always